# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 10:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic', '0002_auto_20190417_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('give_time', models.CharField(max_length=32)),
                ('attendance_rate', models.FloatField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=-1)),
                ('give_time', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Item')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('give_time', models.CharField(max_length=32)),
                ('final_salary', models.FloatField(default=0)),
                ('pay_date', models.CharField(default='', max_length=32)),
                ('status', models.IntegerField(choices=[(0, '\u672a\u53d1\u653e'), (1, '\u5df2\u53d1\u653e')], default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeachRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teach_time', models.FloatField(default='0')),
                ('the_price', models.FloatField(default='0')),
                ('money', models.FloatField()),
                ('give_time', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.TeachItem')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='WaitVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('give_time', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('verify', models.IntegerField(choices=[(0, '\u5f85\u5ba1\u6838'), (1, '\u5ba1\u6838\u901a\u8fc7'), (2, '\u5ba1\u6838\u62d2\u7edd'), (3, '\u6682\u5b58')], default=3)),
                ('work_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='payroll',
            name='verify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.WaitVerify'),
        ),
        migrations.AlterUniqueTogether(
            name='teachroll',
            unique_together=set([('staff', 'teach_time', 'give_time')]),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together=set([('staff', 'item', 'give_time')]),
        ),
    ]
