# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-18 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollrecords',
            name='pay_date',
            field=models.CharField(default='', max_length=64, null=True),
        ),
    ]
