# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20190418_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollrecords',
            name='pay_date',
            field=models.DateField(max_length=64, null=True),
        ),
    ]
