# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20190419_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerate',
            name='give_time',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='give_time',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='payrollrecords',
            name='give_time',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='teachroll',
            name='give_time',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='waitverify',
            name='give_time',
            field=models.CharField(max_length=64),
        ),
    ]
