# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-19 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20190419_0947'),
        ('payroll', '0004_auto_20190419_0947'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachroll',
            unique_together=set([('staff', 'item', 'give_time')]),
        ),
    ]
